[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"
