(()=>{var e={};e.id=1842,e.ids=[1842],e.modules={3295:e=>{"use strict";e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},10846:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},11997:e=>{"use strict";e.exports=require("punycode")},27910:e=>{"use strict";e.exports=require("stream")},29294:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},34631:e=>{"use strict";e.exports=require("tls")},36552:(e,r,t)=>{"use strict";t.r(r),t.d(r,{patchFetch:()=>f,routeModule:()=>h,serverHooks:()=>v,workAsyncStorage:()=>w,workUnitAsyncStorage:()=>_});var s={};t.r(s),t.d(s,{GET:()=>l,POST:()=>d});var a=t(96559),n=t(48088),i=t(37719),o=t(32190),u=t(44999),c=t(61223),p=t(56806);async function d(e){try{let r=(0,c.createRouteHandlerClient)({cookies:u.cookies}),{data:{user:t},error:s}=await r.auth.getUser();if(s||!t)return o.NextResponse.json({error:"Unauthorized"},{status:401});let{action:a,...n}=await e.json();switch(a){case"register_warranty":let{orderId:i,itemId:d,purchaseDate:l,warrantyPeriodMonths:h}=n,w=new Date(l);w.setMonth(w.getMonth()+h);let{data:_,error:v}=await r.from("warranties").insert({user_id:t.id,order_id:i,item_id:d,purchase_date:l,warranty_expiration:w.toISOString(),status:"active"}).select().single();if(v)return o.NextResponse.json({error:"Failed to register warranty"},{status:500});return o.NextResponse.json(_);case"claim_warranty":let{warrantyId:f,claimReason:m,description:g}=n,{data:x,error:y}=await r.from("warranties").select("*").eq("id",f).eq("user_id",t.id).eq("status","active").single();if(y||!x)return o.NextResponse.json({error:"Warranty not found or not active"},{status:404});if(new Date>new Date(x.warranty_expiration))return o.NextResponse.json({error:"Warranty has expired"},{status:400});let{data:S,error:j}=await r.from("warranty_claims").insert({warranty_id:f,claim_reason:m,description:g,status:"pending",claim_date:new Date().toISOString()}).select().single();if(j)return o.NextResponse.json({error:"Failed to create warranty claim"},{status:500});return o.NextResponse.json(S);case"record_construction_warranty":let{projectId:q,itemData:R}=n,N=await p.Ui.recordWarranty(q,t.id,R);return o.NextResponse.json(N);case"update_construction_warranty":let{constructionWarrantyId:k,warrantyStatus:I,claimDetails:D}=n,b=await p.Ui.updateWarrantyStatus(k,I,D);return o.NextResponse.json(b);default:return o.NextResponse.json({error:"Invalid action"},{status:400})}}catch(e){return o.NextResponse.json({error:e instanceof Error?e.message:"Failed to process warranty action"},{status:500})}}async function l(e){try{let r=(0,c.createRouteHandlerClient)({cookies:u.cookies}),{data:{user:t},error:s}=await r.auth.getUser();if(s||!t)return o.NextResponse.json({error:"Unauthorized"},{status:401});let a=e.nextUrl.searchParams;switch(a.get("action")){case"my_warranties":let{data:n,error:i}=await r.from("warranties").select(`
            *,
            global_items (
              name,
              brand,
              image_url
            ),
            warranty_claims (
              id,
              claim_reason,
              status,
              claim_date,
              resolution_date
            )
          `).eq("user_id",t.id).order("purchase_date",{ascending:!1});if(i)return o.NextResponse.json({error:"Failed to fetch warranties"},{status:500});return o.NextResponse.json(n);case"warranty_details":let d=a.get("warrantyId");if(!d)return o.NextResponse.json({error:"Warranty ID is required"},{status:400});let{data:l,error:h}=await r.from("warranties").select(`
            *,
            global_items (
              name,
              brand,
              description,
              image_url,
              specifications
            ),
            warranty_claims (
              id,
              claim_reason,
              description,
              status,
              claim_date,
              resolution_date,
              resolution_notes
            )
          `).eq("id",d).eq("user_id",t.id).single();if(h)return o.NextResponse.json({error:"Warranty not found"},{status:404});return o.NextResponse.json(l);case"expiring_soon":let w=parseInt(a.get("days")||"30",10),_=new Date;_.setDate(_.getDate()+w);let{data:v,error:f}=await r.from("warranties").select(`
            *,
            global_items (
              name,
              brand,
              image_url
            )
          `).eq("user_id",t.id).eq("status","active").gte("warranty_expiration",new Date().toISOString()).lte("warranty_expiration",_.toISOString()).order("warranty_expiration",{ascending:!0});if(f)return o.NextResponse.json({error:"Failed to fetch expiring warranties"},{status:500});return o.NextResponse.json(v);case"project_warranties":let m=a.get("projectId"),g=r.from("warranty_records").select("*").order("created_at",{ascending:!1});if(m)g=g.eq("project_id",m);else{let{data:e}=await r.from("construction_supervisors").select("id").eq("user_id",t.id).single();if(e){let{data:t}=await r.from("construction_contracts").select("project_id").eq("supervisor_id",e.id);t&&t.length>0&&(g=g.in("project_id",t.map(e=>e.project_id)))}}let{data:x,error:y}=await g;if(y)return o.NextResponse.json({error:"Failed to fetch project warranties"},{status:500});return o.NextResponse.json({warranties:x});case"construction_warranties":let S=a.get("projectId");if(!S)return o.NextResponse.json({error:"Project ID is required"},{status:400});let j=await p.Ui.getProjectWarranties(S);return o.NextResponse.json(j);default:return o.NextResponse.json({error:"Invalid action"},{status:400})}}catch(e){return o.NextResponse.json({error:"Failed to fetch warranty data"},{status:500})}}let h=new a.AppRouteRouteModule({definition:{kind:n.RouteKind.APP_ROUTE,page:"/api/warranties/route",pathname:"/api/warranties",filename:"route",bundlePath:"app/api/warranties/route"},resolvedPagePath:"C:\\Users\\hp\\BinnaCodes\\binna\\src\\app\\api\\warranties\\route.ts",nextConfigOutput:"",userland:s}),{workAsyncStorage:w,workUnitAsyncStorage:_,serverHooks:v}=h;function f(){return(0,i.patchFetch)({workAsyncStorage:w,workUnitAsyncStorage:_})}},39727:()=>{},44870:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},47990:()=>{},51906:e=>{function r(e){var r=Error("Cannot find module '"+e+"'");throw r.code="MODULE_NOT_FOUND",r}r.keys=()=>[],r.resolve=r,r.id=51906,e.exports=r},55511:e=>{"use strict";e.exports=require("crypto")},55591:e=>{"use strict";e.exports=require("https")},56806:(e,r,t)=>{"use strict";t.d(r,{Ui:()=>a});let s=(0,t(61223).createClientComponentClient)();class a{async authenticateSupervisor(e,r){try{let{data:t,error:a}=await s.auth.signInWithPassword({email:e,password:r});if(a||!t.user)return null;let{data:n,error:i}=await s.from("supervisors").select("*").eq("user_id",t.user.id).eq("active",!0).single();if(i||!n)return null;let o=this.generateSessionToken(),u=new Date;return u.setHours(u.getHours()+8),await s.from("supervisor_sessions").insert({supervisor_id:n.id,session_token:o,expires_at:u.toISOString()}),this.currentSupervisor=n,this.authToken=o,{supervisor:n,token:o}}catch(e){return null}}async validateSupervisorSession(e){try{let{data:r,error:t}=await s.from("supervisor_sessions").select(`
          *,
          supervisors (*)
        `).eq("session_token",e).gt("expires_at",new Date().toISOString()).single();if(t||!r)return null;return this.currentSupervisor=r.supervisors,this.authToken=e,r.supervisors}catch(e){return null}}async logout(){this.authToken&&await s.from("supervisor_sessions").delete().eq("session_token",this.authToken),this.currentSupervisor=null,this.authToken=null}async requestAuthorization(e){try{let{data:r,error:t}=await s.from("authorization_requests").insert({user_id:e.user_id,action:e.action,resource:e.resource,reason:e.reason,status:"pending",requested_at:new Date().toISOString()}).select().single();if(t)return null;return await this.notifySupervisors(r),r}catch(e){return null}}async getPendingAuthorizations(){try{if(!this.currentSupervisor)throw Error("Not authenticated as supervisor");let{data:e,error:r}=await s.from("authorization_requests").select(`
          *,
          users (name, email)
        `).eq("status","pending").order("requested_at",{ascending:!1});if(r)return[];return e||[]}catch(e){return[]}}async approveAuthorization(e,r){try{if(!this.currentSupervisor)throw Error("Not authenticated as supervisor");let{error:t}=await s.from("authorization_requests").update({status:"approved",approved_at:new Date().toISOString(),approved_by:this.currentSupervisor.id,supervisor_reason:r}).eq("id",e);if(t)return!1;return!0}catch(e){return!1}}async denyAuthorization(e,r){try{if(!this.currentSupervisor)throw Error("Not authenticated as supervisor");let{error:t}=await s.from("authorization_requests").update({status:"denied",approved_at:new Date().toISOString(),approved_by:this.currentSupervisor.id,supervisor_reason:r}).eq("id",e);if(t)return!1;return!0}catch(e){return!1}}hasPermission(e){return!!this.currentSupervisor&&(this.currentSupervisor.permissions.includes(e)||this.currentSupervisor.permissions.includes("*"))}canApprove(e,r){if(!this.currentSupervisor)return!1;let t=`approve:${e}:${r}`,s=`approve:${e}:*`;return this.hasPermission(t)||this.hasPermission(s)||this.hasPermission("approve:*:*")}async approveBalanceAdjustment(e,r,t){try{if(!this.canApprove("balance_adjustment","user_account"))throw Error("Insufficient permissions for balance adjustment");let{error:a}=await s.from("balance_approvals").insert({user_id:e,supervisor_id:this.currentSupervisor.id,amount:r,reason:t,approved_at:new Date().toISOString()});if(a)return!1;let{error:n}=await s.rpc("adjust_user_balance",{user_id:e,amount:r});if(n)return!1;return!0}catch(e){return!1}}generateSessionToken(){return"sup_"+Math.random().toString(36).substr(2,15)+Date.now().toString(36)}async notifySupervisors(e){}getCurrentSupervisor(){return this.currentSupervisor}isAuthenticated(){return null!==this.currentSupervisor&&null!==this.authToken}constructor(){this.currentSupervisor=null,this.authToken=null}}let n=new a},63033:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},74075:e=>{"use strict";e.exports=require("zlib")},78335:()=>{},79428:e=>{"use strict";e.exports=require("buffer")},79551:e=>{"use strict";e.exports=require("url")},81630:e=>{"use strict";e.exports=require("http")},91645:e=>{"use strict";e.exports=require("net")},94735:e=>{"use strict";e.exports=require("events")},96487:()=>{}};var r=require("../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),s=r.X(0,[4243,580,9398,1223,4999],()=>t(36552));module.exports=s})();