(()=>{var e={};e.id=1719,e.ids=[1719],e.modules={3295:e=>{"use strict";e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},8049:(e,r,t)=>{"use strict";t.r(r),t.d(r,{patchFetch:()=>g,routeModule:()=>c,serverHooks:()=>m,workAsyncStorage:()=>x,workUnitAsyncStorage:()=>l});var s={};t.r(s),t.d(s,{GET:()=>d});var i=t(96559),a=t(48088),o=t(37719),n=t(32190),u=t(61223),p=t(44999);async function d(e){try{let r=(0,u.createRouteHandlerClient)({cookies:p.cookies}),{data:{user:t},error:s}=await r.auth.getUser();if(s||!t)return n.NextResponse.json({error:"Unauthorized"},{status:401});let i=e.nextUrl.searchParams,a=i.get("userId"),o=i.get("supervisorId"),d=i.get("projectId");if(!a)return n.NextResponse.json({error:"Missing required parameters"},{status:400});let c=r.from("supervisor_chat_messages").select(`
        id,
        sender_id,
        sender_type,
        sender_name,
        content,
        created_at as timestamp,
        attachment_url,
        read
      `);c=o?c.or(`and(user_id.eq.${a},supervisor_id.eq.${o}),and(user_id.eq.${o},supervisor_id.eq.${a})`):d?c.eq("project_id",d):c.or(`user_id.eq.${a},supervisor_id.eq.${a}`);let{data:x,error:l}=await c.order("created_at",{ascending:!0});if(l)return n.NextResponse.json({error:"Failed to fetch messages"},{status:500});if(x&&x.length>0){let e=x.filter(e=>!1===e.read&&e.sender_id!==t.id).map(e=>e.id);e.length>0&&await r.from("supervisor_chat_messages").update({read:!0,updated_at:new Date().toISOString()}).in("id",e)}return n.NextResponse.json({messages:x||[]})}catch(e){return n.NextResponse.json({error:"Internal Server Error"},{status:500})}}let c=new i.AppRouteRouteModule({definition:{kind:a.RouteKind.APP_ROUTE,page:"/api/chat/messages/route",pathname:"/api/chat/messages",filename:"route",bundlePath:"app/api/chat/messages/route"},resolvedPagePath:"C:\\Users\\hp\\BinnaCodes\\binna\\src\\app\\api\\chat\\messages\\route.ts",nextConfigOutput:"",userland:s}),{workAsyncStorage:x,workUnitAsyncStorage:l,serverHooks:m}=c;function g(){return(0,o.patchFetch)({workAsyncStorage:x,workUnitAsyncStorage:l})}},10846:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},11997:e=>{"use strict";e.exports=require("punycode")},27910:e=>{"use strict";e.exports=require("stream")},29294:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},34631:e=>{"use strict";e.exports=require("tls")},39727:()=>{},44870:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},47990:()=>{},51906:e=>{function r(e){var r=Error("Cannot find module '"+e+"'");throw r.code="MODULE_NOT_FOUND",r}r.keys=()=>[],r.resolve=r,r.id=51906,e.exports=r},55511:e=>{"use strict";e.exports=require("crypto")},55591:e=>{"use strict";e.exports=require("https")},63033:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},74075:e=>{"use strict";e.exports=require("zlib")},78335:()=>{},79428:e=>{"use strict";e.exports=require("buffer")},79551:e=>{"use strict";e.exports=require("url")},81630:e=>{"use strict";e.exports=require("http")},91645:e=>{"use strict";e.exports=require("net")},94735:e=>{"use strict";e.exports=require("events")},96487:()=>{}};var r=require("../../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),s=r.X(0,[4243,580,9398,1223,4999],()=>t(8049));module.exports=s})();