(()=>{var e={};e.id=7021,e.ids=[7021],e.modules={3295:e=>{"use strict";e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},10846:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},29021:e=>{"use strict";e.exports=require("fs")},29294:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},33873:e=>{"use strict";e.exports=require("path")},44870:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},63033:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},78335:()=>{},79748:e=>{"use strict";e.exports=require("fs/promises")},95010:(e,t,r)=>{"use strict";r.r(t),r.d(t,{patchFetch:()=>v,routeModule:()=>w,serverHooks:()=>g,workAsyncStorage:()=>h,workUnitAsyncStorage:()=>y});var s={};r.r(s),r.d(s,{POST:()=>l});var o=r(96559),a=r(48088),n=r(37719),i=r(32190),c=r(79748),p=r(33873),u=r(29021);async function d(e,t){await new Promise(e=>setTimeout(e,2e3));let r=[{vendor:"محل الصالحي لمواد البناء",amount:2450,date:"2025-06-14",category:"مواد البناء",items:["أسمنت بورتلاند 50 كيس","حديد تسليح 12 مم","رمل أبيض 5 متر مكعب"],confidence:.94},{vendor:"مؤسسة النجار للأدوات",amount:890.5,date:"2025-06-14",category:"أدوات ومعدات",items:["مثقاب كهربائي","مفكات متنوعة","شريط قياس"],confidence:.87},{vendor:"مطعم الزعفران",amount:125,date:"2025-06-14",category:"وجبات العمال",items:["وجبة غداء \xd7 5","مشروبات","خدمة التوصيل"],confidence:.91}];return r[Math.floor(Math.random()*r.length)]}async function m(e){let t=process.env.OPENAI_API_KEY;if(!t)throw Error("OpenAI API key not configured");let r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-4",messages:[{role:"system",content:`أنت نظام ذكي لاستخراج بيانات الفواتير والإيصالات. استخرج المعلومات التالية من النص باللغة العربية واستخرجها بتنسيق JSON:
          {
            "vendor": "اسم المورد أو المتجر",
            "amount": رقم المبلغ الإجمالي,
            "date": "التاريخ بتنسيق YYYY-MM-DD",
            "category": "فئة المصروف (مواد البناء، أدوات، وجبات، إلخ)",
            "items": ["قائمة بالعناصر المشتراة"],
            "confidence": رقم من 0 إلى 1 يمثل مستوى الثقة في الاستخراج
          }`},{role:"user",content:e}],temperature:.1})});if(!r.ok)throw Error("Failed to process with OpenAI");return JSON.parse((await r.json()).choices[0].message.content)}async function l(e){try{let t,r=await e.formData(),s=r.get("file"),o=r.get("userId");if(!s)return i.NextResponse.json({error:"لم يتم تحديد ملف"},{status:400});let a=(0,p.join)(process.cwd(),"uploads","receipts");(0,u.existsSync)(a)||await (0,c.mkdir)(a,{recursive:!0});let n=await s.arrayBuffer(),l=Buffer.from(n),w=`${o}-${Date.now()}-${s.name}`,h=(0,p.join)(a,w);if(await (0,c.writeFile)(h,l),process.env.OPENAI_API_KEY){let e=await f(l,s.type);t=await m(e)}else t=await d(l,w);return await x(o,w,t),i.NextResponse.json({success:!0,expenseData:t,fileName:w,message:"تم معالجة الفاتورة بنجاح"})}catch(e){return i.NextResponse.json({error:"فشل في معالجة الفاتورة"},{status:500})}}async function f(e,t){return`
  فاتورة رقم: 2025001
  التاريخ: 14/06/2025
  محل الصالحي لمواد البناء
  العنوان: الرياض، المملكة العربية السعودية
  
  أسمنت بورتلاند 50 كيس \xd7 15 ريال = 750 ريال
  حديد تسليح 12 مم \xd7 5 طن \xd7 300 ريال = 1500 ريال  
  رمل أبيض 5 متر مكعب \xd7 40 ريال = 200 ريال
  
  المجموع الفرعي: 2450 ريال
  ضريبة القيمة المضافة (15%): 367.50 ريال
  المجموع الإجمالي: 2817.50 ريال
  `}async function x(e,t,r){}let w=new o.AppRouteRouteModule({definition:{kind:a.RouteKind.APP_ROUTE,page:"/api/ai/process-receipt/route",pathname:"/api/ai/process-receipt",filename:"route",bundlePath:"app/api/ai/process-receipt/route"},resolvedPagePath:"C:\\Users\\hp\\BinnaCodes\\binna\\src\\app\\api\\ai\\process-receipt\\route.ts",nextConfigOutput:"",userland:s}),{workAsyncStorage:h,workUnitAsyncStorage:y,serverHooks:g}=w;function v(){return(0,n.patchFetch)({workAsyncStorage:h,workUnitAsyncStorage:y})}},96487:()=>{}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[4243,580],()=>r(95010));module.exports=s})();